- name: Create Ansible Jobs
  hosts: localhost
  vars:
    jenkins_url: http://172.31.81.197:8080
    jenkins_user: admin
    jenkins_password: "{{ lookup('aws_ssm', 'jenkins_password', region='us-east-1' ) }}"
  tasks:
    - name: Create Jenkins Jobs - Frontend
      community.general.jenkins_job:
        config: "{{ lookup('template', 'mjob.xml') }}"
        name: frontend
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: frontend
        auto_trigger: "true"
        file_name: Jenkinsfile

    - name: Create Jenkins Jobs - Backend
      community.general.jenkins_job:
        config: "{{ lookup('template', 'mjob.xml') }}"
        name: backend
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: backend
        auto_trigger: "true"
        file_name: Jenkinsfile

    - name: Create Jenkins Jobs - Schema Load
      community.general.jenkins_job:
        config: "{{ lookup('template', 'mjob.xml') }}"
        name: schema_load
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: expense_schema_load
        auto_trigger: "true"
        file_name: Jenkinsfile

    - name: Create Jenkins Jobs - Config Parameter Init Container
      community.general.jenkins_job:
        config: "{{ lookup('template', 'mjob.xml') }}"
        name: init_container
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: expense_parameter_init_container
        auto_trigger: "true"
        file_name: Jenkinsfile

    - name: Create Jenkins Jobs - Expense Parameters
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: expense-parameters
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: parameter_store
        auto_trigger: "false"
        file_name: Jenkinsfile

    - name: Create Jenkins Jobs - Expense Terraform
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: expense-terraform
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: expense_terraform
        auto_trigger: "false"
        file_name: Jenkinsfile

    - name: Create Jenkins Jobs - Mutable Deployment
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: mutable-deployment
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: infra_ansible
        auto_trigger: "false"
        file_name: Jenkinsfile-Mutable

    - name: Create Jenkins Jobs - Helm Deployment
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: helm-deployment
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: expense_helm_chart
        auto_trigger: "false"
        file_name: Jenkinsfile